   $(document).ready(function(){
    $("#image1").click(function(){
      $(".design-text").show('1500');
      $("#image1").hide();
    });
    $(".design-text").click(function(){
      $("#image1").show('1500');
      $(".design-text").hide();
  });
});
  
$(document).ready(function(){
    $("#image2").click(function(){
      $(".development-text").show('1500');
      $("#image2").hide();
    });
    $(".development-text").click(function(){
      $("#image2").show('1500');
      $(".development-text").hide();
  });
});

$(document).ready(function(){
    $("#image3").click(function(){
      $(".product-text").show('1500');
      $("#image3").hide();
    });
    $(".product-text").click(function(){
      $("#image3").show('1500');
      $(".product-text").hide();
  });
});

$(document).ready(function(){
     $("#img1").mouseover(function(){   
     $("#overlay1").show();
   }).mouseout(function(){
   $("#overlay1").hide();
});
   });
  $(document).ready(function(){
    $("#img2").mouseover(function(){
      $("#overlay2").show();
    }).mouseout(function(){
      $("#overlay2").hide();
    });
  });
  $(document).ready(function(){
    $("#img3").mouseover(function(){
      $("#overlay3").show();
    }).mouseout(function(){
      $("#overlay3").hide();
    });
  });
  $(document).ready(function(){
    $("#img4").mouseover(function(){
      $("#overlay4").show();
    }).mouseout(function(){
      $("#overlay4").hide();
    });
  });
  
  $(document).ready(function(){
    $("#img5").mouseover(function(){
      $("#overlay5").show();
    }).mouseout(function(){
      $("#overlay5").hide();
    });
    $("#img6").mouseover(function(){
      $("#overlay6").show();
    }).mouseout(function(){
      $("#overlay6").hide();
    });
    $("#img7").mouseover(function(){
      $("#overlay7").show();
    }).mouseout(function(){
      $("#overlay7").hide();
    });
    $("#img8").mouseover(function(){
      $("#overlay8").show();
    }).mouseout(function(){
      $("#overlay8").hide();
    });
  });